# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: 
      - master
    tags:        
      - v* 
  pull_request:
    branches: 
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    strategy:
      matrix:
        runner: [ubuntu-latest]
    runs-on:
      - ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Test
        run: cd ldap-rest-api; mvn clean test
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          file: ./ldap-rest-api/target/site/jacoco/jacoco.xml
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)